"""Static finding registry for the built-in OpenBot Data audit rule pack."""

from __future__ import annotations

from types import MappingProxyType
from typing import Mapping, Tuple

from openbot_data.audit.models import CapabilityRequirement, RuleSpec


class UnknownFindingCodeError(LookupError):
    """Raised when implementation emits an unregistered stable finding code."""


def _fixture_id(code: str, outcome: str) -> str:
    return f"audit:{code.lower()}:{outcome}"


def _spec(
    code: str,
    severity: str,
    layer: str,
    message: str,
    impact: str,
    fixability: str,
    *,
    applies_to: Tuple[str, ...] = ("video", "lerobot"),
    requirements: Tuple[CapabilityRequirement, ...] = (),
    evidence_fields: Tuple[str, ...] = (),
    location_fields: Tuple[str, ...] = (),
    ordering_fields: Tuple[str, ...] = (),
) -> RuleSpec:
    return RuleSpec(
        rule_id=code.lower().replace("_", "."),
        code=code,
        layer=layer,  # type: ignore[arg-type]
        default_severity=severity,  # type: ignore[arg-type]
        message=message,
        applies_to=applies_to,
        requirements=requirements,
        evidence_fields=evidence_fields,
        location_fields=location_fields,
        impact=impact,
        fixability=fixability,  # type: ignore[arg-type]
        remediation_ref=f"openbot://remediation/{code}",
        ordering_fields=ordering_fields or location_fields,
        positive_fixture=_fixture_id(code, "positive"),
        negative_fixture=_fixture_id(code, "negative"),
    )


_MEDIA_METADATA_AVAILABLE = (
    CapabilityRequirement("media.metadata", coverage="available"),
)
_MEDIA_DECODE_AVAILABLE = (
    CapabilityRequirement(
        "media.decode",
        minimum_integrity="sample",
        coverage="available",
    ),
)
_CHECKSUM_AVAILABLE = (
    CapabilityRequirement("content.checksum", coverage="available"),
)

_LAYERED_VALIDATION_FINDINGS = (
    (
        "LEROBOT_FRAME_COUNT_MISMATCH",
        "error",
        "alignment",
        "Declared and validated frame counts differ.",
        "declared_frame_extent_is_stale",
    ),
    (
        "LEROBOT_TASK_COUNT_MISMATCH",
        "error",
        "alignment",
        "Declared and validated task counts differ.",
        "declared_task_extent_is_stale",
    ),
    (
        "LEROBOT_VIDEO_COUNT_MISMATCH",
        "error",
        "alignment",
        "Declared and validated video counts differ.",
        "declared_media_extent_is_stale",
    ),
    (
        "LEROBOT_DATA_SHARD_COUNT_MISMATCH",
        "error",
        "alignment",
        "Declared and validated data-shard counts differ.",
        "declared_data_extent_is_stale",
    ),
    (
        "LEROBOT_EPISODE_INDEX_NON_CONTIGUOUS",
        "error",
        "alignment",
        "Episode indexes are not contiguous.",
        "episode_order_is_incomplete",
    ),
    (
        "LEROBOT_EPISODE_RANGE_INVALID",
        "error",
        "alignment",
        "An episode data range is invalid.",
        "episode_data_window_is_invalid",
    ),
    (
        "LEROBOT_EPISODE_RANGE_LENGTH_MISMATCH",
        "error",
        "alignment",
        "An episode range does not match its declared length.",
        "episode_frame_extent_is_inconsistent",
    ),
    (
        "LEROBOT_EPISODE_RANGE_GAP",
        "error",
        "alignment",
        "Episode data ranges contain a gap.",
        "dataset_frame_ledger_is_incomplete",
    ),
    (
        "LEROBOT_EPISODE_RANGE_OVERLAP",
        "error",
        "alignment",
        "Episode data ranges overlap.",
        "dataset_frame_ledger_is_ambiguous",
    ),
    (
        "LEROBOT_EPISODE_RANGE_OUT_OF_BOUNDS",
        "error",
        "alignment",
        "An episode range extends beyond its data shard.",
        "episode_data_window_is_unreadable",
    ),
    (
        "LEROBOT_PARQUET_UNFINALIZED",
        "error",
        "data",
        "A Parquet artifact appears incomplete or unfinalized.",
        "parquet_payload_is_not_durable",
    ),
    (
        "LEROBOT_PARQUET_SCHEMA_UNREADABLE",
        "error",
        "schema",
        "A Parquet schema cannot be read.",
        "feature_contract_cannot_be_validated",
    ),
    (
        "LEROBOT_PARQUET_ROW_GROUP_UNREADABLE",
        "error",
        "data",
        "A Parquet row group cannot be read.",
        "frame_payload_cannot_be_validated",
    ),
    (
        "LEROBOT_PARQUET_ROW_INVALID",
        "error",
        "data",
        "A Parquet row is not a valid record.",
        "frame_payload_is_malformed",
    ),
    (
        "LEROBOT_FEATURE_COLUMN_MISSING",
        "error",
        "schema",
        "A declared feature column is missing.",
        "declared_training_input_is_unavailable",
    ),
    (
        "LEROBOT_FEATURE_COLUMN_UNDECLARED",
        "warning",
        "schema",
        "A data column is not declared in the feature contract.",
        "payload_schema_has_unreviewed_extensions",
    ),
    (
        "LEROBOT_FEATURE_DTYPE_MISMATCH",
        "error",
        "schema",
        "A feature column dtype differs from its declaration.",
        "training_tensor_dtype_is_incompatible",
    ),
    (
        "LEROBOT_FEATURE_SHAPE_MISMATCH",
        "error",
        "schema",
        "A feature value shape differs from its declaration.",
        "training_tensor_shape_is_incompatible",
    ),
    (
        "LEROBOT_FEATURE_NULLABILITY_MISMATCH",
        "error",
        "schema",
        "A required feature contains null values.",
        "required_training_values_are_missing",
    ),
    (
        "LEROBOT_DATA_ROW_COUNT_MISMATCH",
        "error",
        "data",
        "A data shard row count differs from its prepared extent.",
        "data_shard_extent_is_inconsistent",
    ),
    (
        "LEROBOT_EPISODE_ROW_COUNT_MISMATCH",
        "error",
        "alignment",
        "Observed episode rows differ from the declared episode length.",
        "episode_frame_extent_is_inconsistent",
    ),
    (
        "LEROBOT_FRAME_INDEX_DUPLICATE",
        "error",
        "alignment",
        "A frame index is duplicated within an episode.",
        "episode_frame_order_is_ambiguous",
    ),
    (
        "LEROBOT_FRAME_INDEX_NON_CONTIGUOUS",
        "error",
        "alignment",
        "Frame indexes are not contiguous within an episode.",
        "episode_frame_order_is_incomplete",
    ),
    (
        "LEROBOT_GLOBAL_INDEX_DUPLICATE",
        "error",
        "alignment",
        "A dataset-global row index is duplicated.",
        "dataset_frame_order_is_ambiguous",
    ),
    (
        "LEROBOT_GLOBAL_INDEX_NON_CONTIGUOUS",
        "error",
        "alignment",
        "Dataset-global row indexes are not contiguous.",
        "dataset_frame_order_is_incomplete",
    ),
    (
        "LEROBOT_NUMERIC_NON_FINITE",
        "error",
        "data",
        "A required numeric value is NaN or infinite.",
        "training_numeric_payload_is_unsafe",
    ),
    (
        "LEROBOT_TASK_REFERENCE_INVALID",
        "error",
        "alignment",
        "A frame or episode references an unknown task.",
        "task_annotation_relation_is_invalid",
    ),
    (
        "LEROBOT_TIMESTAMP_NON_MONOTONIC",
        "error",
        "alignment",
        "Episode timestamps are not strictly monotonic.",
        "temporal_order_is_invalid",
    ),
    (
        "LEROBOT_TIMESTAMP_OFF_GRID",
        "error",
        "alignment",
        "A timestamp falls outside the declared FPS grid tolerance.",
        "temporal_sampling_is_inconsistent",
    ),
    (
        "LEROBOT_VIDEO_COVERAGE_MISSING",
        "error",
        "media",
        "A declared episode camera has no readable media relation.",
        "declared_camera_observation_is_unavailable",
    ),
    (
        "LEROBOT_VIDEO_RESOLUTION_MISMATCH",
        "error",
        "media",
        "Observed video resolution differs from its declaration.",
        "camera_tensor_shape_is_incompatible",
    ),
    (
        "LEROBOT_VIDEO_FPS_MISMATCH",
        "error",
        "media",
        "Observed video FPS differs from its declaration.",
        "camera_timing_is_incompatible",
    ),
    (
        "LEROBOT_VIDEO_CHANNELS_MISMATCH",
        "error",
        "media",
        "Observed video channel count differs from its declaration.",
        "camera_tensor_channels_are_incompatible",
    ),
    (
        "LEROBOT_STATS_MISSING",
        "warning",
        "metadata",
        "Stored normalization statistics are missing.",
        "normalization_contract_is_unverified",
    ),
    (
        "LEROBOT_STATS_FIELD_MISSING",
        "warning",
        "metadata",
        "A required normalization statistic field is missing.",
        "normalization_contract_is_incomplete",
    ),
    (
        "LEROBOT_STATS_SHAPE_MISMATCH",
        "error",
        "alignment",
        "Stored statistic shape differs from the feature shape.",
        "normalization_tensor_shape_is_invalid",
    ),
    (
        "LEROBOT_STATS_COUNT_MISMATCH",
        "error",
        "alignment",
        "Stored statistic count differs from validated rows.",
        "normalization_population_is_stale",
    ),
    (
        "LEROBOT_STATS_NON_FINITE",
        "error",
        "data",
        "Stored normalization statistics contain NaN or infinity.",
        "normalization_values_are_unsafe",
    ),
    (
        "LEROBOT_STATS_VALUE_MISMATCH",
        "error",
        "alignment",
        "Stored statistics differ from full-data recomputation.",
        "normalization_values_are_stale",
    ),
)


def _layered_validation_specs() -> Tuple[RuleSpec, ...]:
    return tuple(
        _spec(
            code,
            severity,
            layer,
            message,
            impact,
            "manual" if severity == "warning" else "delegated",
            applies_to=("lerobot",),
        )
        for code, severity, layer, message, impact in _LAYERED_VALIDATION_FINDINGS
    )


_SPECS = (
    *_layered_validation_specs(),
    _spec(
        "DATASET_NOT_FOUND",
        "error",
        "provenance",
        "The requested dataset directory does not exist.",
        "source_cannot_be_resolved",
        "manual",
        location_fields=("source_locator",),
    ),
    _spec(
        "DATASET_INVALID_ARGUMENT",
        "error",
        "provenance",
        "Input format or checksum configuration is unsupported.",
        "audit_cannot_execute",
        "manual",
        evidence_fields=("argument", "value"),
        location_fields=("argument",),
    ),
    _spec(
        "DATASET_PATH_OUTSIDE_ROOT",
        "error",
        "provenance",
        "A media path or symlink resolves outside the dataset root.",
        "dataset_boundary_is_unsafe",
        "manual",
        evidence_fields=("symlink",),
    ),
    _spec(
        "DATASET_SYMLINK_SKIPPED",
        "warning",
        "provenance",
        "A media symlink was skipped by the active source policy.",
        "media_coverage_is_incomplete",
        "manual",
        evidence_fields=("follow_symlinks",),
    ),
    _spec(
        "DATASET_SYMLINK_BROKEN",
        "error",
        "provenance",
        "An opted-in media symlink does not resolve to a file.",
        "referenced_media_is_unavailable",
        "manual",
    ),
    _spec(
        "HUB_PARTIAL_COVERAGE",
        "warning",
        "provenance",
        "The Hub audit intentionally checked only part of the pinned dataset.",
        "dataset_validation_coverage_is_partial",
        "manual",
        applies_to=("lerobot",),
        evidence_fields=("integrity", "skipped_capabilities"),
    ),
    _spec(
        "HUB_DOWNLOAD_BUDGET_EXHAUSTED",
        "warning",
        "provenance",
        "A Hub payload download stopped before exceeding its configured budget.",
        "dataset_validation_coverage_is_budget_limited",
        "manual",
        applies_to=("lerobot",),
        evidence_fields=("exhausted_limits", "effective_budgets"),
    ),
    _spec(
        "HUB_PUBLICATION_METADATA_MISSING",
        "warning",
        "provenance",
        "Optional Hub publication metadata is missing.",
        "publication_metadata_needs_review",
        "manual",
        applies_to=("lerobot",),
        evidence_fields=("missing",),
    ),
    _spec(
        "LEROBOT_INFO_MISSING",
        "error",
        "metadata",
        "LeRobot meta/info.json is missing.",
        "format_contract_cannot_be_resolved",
        "delegated",
        applies_to=("lerobot",),
    ),
    _spec(
        "LEROBOT_CODEBASE_VERSION_MISSING",
        "error",
        "metadata",
        "LeRobot codebase_version is missing.",
        "format_adapter_cannot_be_selected",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("supported_contracts",),
    ),
    _spec(
        "LEROBOT_CODEBASE_VERSION_INVALID",
        "error",
        "metadata",
        "LeRobot codebase_version is not a valid version string.",
        "format_adapter_cannot_be_selected",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("declared_version", "value_type"),
    ),
    _spec(
        "LEROBOT_CODEBASE_VERSION_UNTESTED",
        "warning",
        "metadata",
        "LeRobot version is being inspected with a same-major provisional adapter.",
        "format_compatibility_is_not_conformance_tested",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=(
            "declared_version",
            "selected_adapter",
            "supported_contract",
            "compatibility_kind",
        ),
    ),
    _spec(
        "LEROBOT_CODEBASE_VERSION_UNSUPPORTED",
        "error",
        "metadata",
        "LeRobot major version is unsupported.",
        "format_contract_is_incompatible",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("declared_version", "declared_major", "supported_contracts"),
    ),
    _spec(
        "LEROBOT_V21_MIGRATION_RECOMMENDED",
        "info",
        "provenance",
        "LeRobot v2.1 should be migrated on a reviewed copy before use with "
        "the pinned v3 toolchain.",
        "legacy_dataset_requires_explicit_migration_for_v3_tooling",
        "manual",
        applies_to=("lerobot",),
        evidence_fields=(
            "source_contract",
            "target_contract",
            "package",
            "module",
            "mutates_source",
            "openbot_will_execute",
        ),
    ),
    _spec(
        "LEROBOT_LAYOUT_VERSION_MISMATCH",
        "error",
        "metadata",
        "LeRobot files do not match the declared storage-contract version.",
        "format_layout_is_ambiguous",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("adapter_id", "legacy_paths", "records_mixed"),
    ),
    _spec(
        "LEROBOT_METADATA_INVALID",
        "error",
        "metadata",
        "LeRobot JSON metadata cannot be parsed as an object.",
        "format_contract_cannot_be_parsed",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("error",),
        location_fields=("line",),
    ),
    _spec(
        "LEROBOT_EPISODES_MISSING",
        "error",
        "metadata",
        "No JSONL or parquet episode metadata exists.",
        "episode_inventory_is_unavailable",
        "delegated",
        applies_to=("lerobot",),
    ),
    _spec(
        "LEROBOT_EPISODES_UNREADABLE",
        "error",
        "metadata",
        "Episode JSONL or parquet metadata cannot be read.",
        "episode_inventory_is_incomplete",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("error",),
    ),
    _spec(
        "LEROBOT_TASKS_MISSING",
        "error",
        "metadata",
        "Required LeRobot task metadata is missing.",
        "task_inventory_is_unavailable",
        "delegated",
        applies_to=("lerobot",),
    ),
    _spec(
        "LEROBOT_TASKS_UNREADABLE",
        "error",
        "metadata",
        "LeRobot task metadata cannot be read.",
        "task_inventory_is_incomplete",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("error", "artifact_role", "reason"),
        location_fields=("line", "row"),
    ),
    _spec(
        "LEROBOT_TASK_INVALID",
        "error",
        "metadata",
        "A LeRobot task metadata record is malformed.",
        "task_identity_is_invalid",
        "delegated",
        applies_to=("lerobot",),
        location_fields=("line", "row", "task_index"),
    ),
    _spec(
        "LEROBOT_STATS_INVALID",
        "error",
        "metadata",
        "LeRobot normalization statistics metadata cannot be read.",
        "normalization_contract_is_unavailable",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("error",),
    ),
    _spec(
        "LEROBOT_DEPENDENCY_MISSING",
        "error",
        "metadata",
        "Parquet discovery requires an unavailable optional dependency.",
        "parquet_validation_cannot_execute",
        "manual",
        applies_to=("lerobot",),
        evidence_fields=("install",),
    ),
    _spec(
        "LEROBOT_EPISODE_INVALID",
        "error",
        "metadata",
        "An episode metadata record is malformed.",
        "episode_record_cannot_be_parsed",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("error",),
        location_fields=("line", "record"),
        ordering_fields=("line", "record"),
    ),
    _spec(
        "LEROBOT_EPISODE_INDEX_INVALID",
        "error",
        "data",
        "An episode has no valid integer index.",
        "episode_identity_is_invalid",
        "delegated",
        applies_to=("lerobot",),
        location_fields=("record", "episode_index"),
    ),
    _spec(
        "LEROBOT_EPISODE_LENGTH_INVALID",
        "error",
        "data",
        "An episode length is not a non-negative integer.",
        "episode_extent_is_invalid",
        "delegated",
        applies_to=("lerobot",),
        location_fields=("episode_index", "record"),
    ),
    _spec(
        "LEROBOT_EPISODE_INDEX_DUPLICATE",
        "error",
        "data",
        "An episode index occurs in more than one metadata record.",
        "episode_identity_is_ambiguous",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("records", "count"),
        location_fields=("episode_index",),
    ),
    _spec(
        "LEROBOT_EPISODE_COUNT_MISMATCH",
        "error",
        "alignment",
        "Declared and discovered episode counts differ.",
        "declared_totals_do_not_match_content",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("declared", "discovered"),
    ),
    _spec(
        "LEROBOT_DATA_PATH_TEMPLATE_INVALID",
        "error",
        "metadata",
        "The declared LeRobot data path template is invalid.",
        "data_shards_cannot_be_resolved",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("reason", "required_placeholders"),
    ),
    _spec(
        "LEROBOT_DATA_RELATION_MISSING",
        "error",
        "alignment",
        "A LeRobot v3 episode lacks a complete data-shard relation.",
        "episode_data_relation_is_incomplete",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("missing",),
        location_fields=("episode_index", "row"),
    ),
    _spec(
        "LEROBOT_DATA_RELATION_INVALID",
        "error",
        "alignment",
        "A LeRobot v3 data-shard relation contains invalid indexes.",
        "episode_data_relation_is_invalid",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("invalid_fields",),
        location_fields=("episode_index", "row"),
    ),
    _spec(
        "LEROBOT_DATA_MISSING",
        "error",
        "data",
        "A required or referenced LeRobot data shard is missing.",
        "frame_payload_is_unavailable",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("declared_total_frames",),
        location_fields=("episode_index",),
    ),
    _spec(
        "LEROBOT_DATA_UNREADABLE",
        "error",
        "data",
        "A LeRobot data Parquet footer or row group cannot be read.",
        "frame_payload_cannot_be_validated",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("reason", "error"),
    ),
    _spec(
        "LEROBOT_VIDEO_MISSING",
        "error",
        "alignment",
        "An episode's local video reference is missing.",
        "episode_media_relation_is_incomplete",
        "manual",
        applies_to=("lerobot",),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("episode_index", "video_key"),
    ),
    _spec(
        "LEROBOT_VIDEO_RELATION_MISSING",
        "error",
        "alignment",
        "A LeRobot v3 episode lacks declared video shard relation metadata.",
        "episode_media_relation_is_incomplete",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("missing",),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("episode_index", "video_key"),
    ),
    _spec(
        "LEROBOT_VIDEO_RELATION_INVALID",
        "error",
        "alignment",
        "A LeRobot v3 video shard relation contains invalid indexes.",
        "episode_media_relation_is_invalid",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("invalid_fields",),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("episode_index", "video_key"),
    ),
    _spec(
        "LEROBOT_VIDEO_PATH_TEMPLATE_INVALID",
        "error",
        "metadata",
        "The declared LeRobot v3 video path template is invalid.",
        "video_shards_cannot_be_resolved",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("reason", "required_placeholders"),
        location_fields=("episode_index", "video_key"),
    ),
    _spec(
        "LEROBOT_VIDEO_PATH_INVALID",
        "error",
        "alignment",
        "An episode video path is not portable and dataset-relative.",
        "episode_media_relation_is_unsafe",
        "delegated",
        applies_to=("lerobot",),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("episode_index", "video_key"),
    ),
    _spec(
        "LEROBOT_VIDEO_SEGMENT_BOUNDS_INVALID",
        "error",
        "alignment",
        "Video segment timestamps are invalid or unordered.",
        "episode_media_window_is_invalid",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("reason", "missing"),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("episode_index", "video_key"),
    ),
    _spec(
        "LEROBOT_VIDEO_SEGMENT_OVERLAP",
        "error",
        "alignment",
        "Two episodes overlap in one camera and shared video shard.",
        "episode_media_windows_are_ambiguous",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=("previous_episode_index", "previous_range", "range"),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("video_key", "episode_index"),
    ),
    _spec(
        "LEROBOT_VIDEO_SEGMENT_OUT_OF_RANGE",
        "error",
        "alignment",
        "A segment extends beyond its referenced video duration.",
        "episode_media_window_is_unreadable",
        "delegated",
        applies_to=("lerobot",),
        evidence_fields=(
            "from_timestamp",
            "to_timestamp",
            "duration_seconds",
            "tolerance_seconds",
        ),
        location_fields=("episode_index", "video_key"),
        ordering_fields=("video_key", "episode_index"),
    ),
    _spec(
        "LEROBOT_VIDEOS_MISSING",
        "error",
        "media",
        "Video streams are declared but no local video files exist.",
        "declared_media_is_unavailable",
        "manual",
        applies_to=("lerobot",),
        evidence_fields=("video_keys",),
    ),
    _spec(
        "VIDEO_UNREADABLE",
        "error",
        "media",
        "A video cannot be opened as a non-empty stream.",
        "media_payload_is_unusable",
        "delegated",
        requirements=_MEDIA_METADATA_AVAILABLE,
        evidence_fields=("error",),
        location_fields=("video_key",),
    ),
    _spec(
        "VIDEO_INVALID_FPS",
        "error",
        "media",
        "Video FPS is zero or negative.",
        "media_timing_is_unusable",
        "delegated",
        requirements=_MEDIA_METADATA_AVAILABLE,
        evidence_fields=("fps",),
        location_fields=("video_key",),
    ),
    _spec(
        "VIDEO_INVALID_DURATION",
        "error",
        "media",
        "Video duration is zero or negative.",
        "media_timing_is_unusable",
        "delegated",
        requirements=_MEDIA_METADATA_AVAILABLE,
        evidence_fields=("duration",),
        location_fields=("video_key",),
    ),
    _spec(
        "VIDEO_INVALID_DIMENSIONS",
        "error",
        "media",
        "Video width or height is zero or negative.",
        "media_shape_is_unusable",
        "delegated",
        requirements=_MEDIA_METADATA_AVAILABLE,
        evidence_fields=("width", "height"),
        location_fields=("video_key",),
    ),
    _spec(
        "VIDEO_PREVIEW_DECODE_FAILED",
        "error",
        "media",
        "A requested deterministic video decode probe failed.",
        "media_payload_cannot_be_verified",
        "delegated",
        requirements=_MEDIA_DECODE_AVAILABLE,
        evidence_fields=("integrity_level", "decoded_frame_count"),
        location_fields=("video_key",),
    ),
    _spec(
        "STREAM_INCONSISTENT_RESOLUTION",
        "warning",
        "media",
        "One camera stream contains multiple resolutions.",
        "camera_batches_may_require_shape_transforms",
        "delegated",
        requirements=_MEDIA_METADATA_AVAILABLE,
        evidence_fields=("resolutions",),
        location_fields=("video_key",),
    ),
    _spec(
        "STREAM_INCONSISTENT_FPS",
        "warning",
        "media",
        "One camera stream contains multiple FPS values.",
        "camera_batches_may_require_timing_transforms",
        "delegated",
        requirements=_MEDIA_METADATA_AVAILABLE,
        evidence_fields=("fps",),
        location_fields=("video_key",),
    ),
    _spec(
        "DUPLICATE_CONTENT",
        "warning",
        "provenance",
        "Multiple files have identical SHA-256 content.",
        "dataset_membership_may_contain_duplicates",
        "manual",
        requirements=_CHECKSUM_AVAILABLE,
        evidence_fields=("checksum_sha256", "paths"),
    ),
)


def _build_registry(specs: Tuple[RuleSpec, ...]) -> Mapping[str, RuleSpec]:
    registry = {}
    for spec in specs:
        if spec.code in registry:
            raise RuntimeError(f"duplicate finding registry code: {spec.code}")
        registry[spec.code] = spec
    return MappingProxyType(registry)


FINDING_REGISTRY: Mapping[str, RuleSpec] = _build_registry(_SPECS)


def get_rule_spec(
    code: str,
    *,
    unknown_policy: str = "error",
) -> RuleSpec:
    """Return registered metadata or an explicit conservative fallback."""
    try:
        return FINDING_REGISTRY[code]
    except KeyError as exc:
        if unknown_policy == "error":
            raise UnknownFindingCodeError(
                f"Finding code {code!r} is not present in the static registry"
            ) from exc
        if unknown_policy != "fallback":
            raise ValueError("unknown_policy must be 'error' or 'fallback'") from exc
        # Unknown implementation output must never become less blocking merely
        # because it supplied its own unregistered severity.
        severity = "error"
        return _spec(
            code=code,
            severity=severity,
            layer="provenance",
            message="An unregistered finding was emitted by the audit implementation.",
            impact="validation_contract_is_unknown",
            fixability="not_repairable",
            applies_to=("*",),
        )
